clone_depth: 1
version: '{branch}-{build}'
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: 'GD.Calculator.csproj' # Use wildcard when it's able to exclude Xamarin projects
  version: '0.0.{build}'
cache:
  - '%LOCALAPPDATA%\NuGet\v3-cache -> appveyor.yml'
before_build:
  - ps: dotnet --info # Useful when version mismatch between CI and local
  - ps: dotnet restore GD.DifficultyCalculator.sln --verbosity quiet # Only nuget.exe knows .NET Core projects
build:
  project: GD.DifficultyCalculator.sln
  parallel: true
  verbosity: minimal
  publish_nuget: true
after_build:
  - ps: dotnet tool restore
  - ps: dotnet format --workspace GD.DifficultyCalculator.sln --dry-run --check
  - ps: .\InspectCode.ps1